---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Nuxt
    image: geerlingguy/docker-ubuntu1804-ansible
    privileged: True
    pre_build_image: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../../../docker_module/site.yml
verifier:
  name: ansible
