  - name: Nuxt container
    docker_container:
      name: NuxtContainer
      image: yuta28/ansible-test:Nuxtimage
      state: started
      ports:
        - "127.0.0.1:8080:3000"
      tty: true
      detach: true
    register: contaier_result

  - debug: var=contaier_result
